flasher
=======

== Status

TravisCI: image:https://travis-ci.org/muhkuh-sys/org.muhkuh.tools-flasher.svg?branch=master["TravisCI build status", link="https://travis-ci.org/muhkuh-sys/org.muhkuh.tools-flasher"]

AppVeyor: image:https://ci.appveyor.com/api/projects/status/github/muhkuh-sys/org.muhkuh.tools-flasher?svg=true["AppVeyor build status", link="https://ci.appveyor.com/project/docbacardi/org-muhkuh-tools-flasher"]

circleci: image:https://circleci.com/gh/muhkuh-sys/org.muhkuh.tools-flasher.svg?style=shield["circleci build status", link="https://circleci.com/gh/muhkuh-sys/org.muhkuh.tools-flasher"]


== About

The flasher is an application for systems based on the Hilscher "netX" CPU. It writes data to flash or EEPROM chips.

The flasher is a stand-alone application. This means it does not require an OS like Linux, WindowsCE or the netX specific rcX.
It's main use is writing bootable images to SPI or parallel flashes, but it can also be used to:

 * write flashdisk images or application specific data
 * erase a bootable image
 * read the contents of a flash device


== Infrastructure

This chapter describes the current infrastructure of the project.

The flasher source code is hosted on GitHub: https://github.com/muhkuh-sys/org.muhkuh.tools-flasher

Issues are collected here: https://github.com/muhkuh-sys/org.muhkuh.tools-flasher/issues

Each push to the GitHub repository triggers a build on TravisCI using a Ubuntu 12.04 64bit VM: https://travis-ci.org/muhkuh-sys/org.muhkuh.tools-flasher . Another build is triggered on AppVeyor running on 32bit and 64bit Windows: https://ci.appveyor.com/project/docbacardi/org-muhkuh-tools-flasher .
Each push to the GitHub repository triggers a build on these services:

 * TravisCI using a Ubuntu 12.04 64bit VM: https://travis-ci.org/muhkuh-sys/org.muhkuh.tools-flasher
 * AppVeyor running on 32bit and 64bit Windows: https://ci.appveyor.com/project/docbacardi/org-muhkuh-tools-flasher
 * circleci running on Ubuntu 12.04 64bit VM: https://circleci.com/gh/muhkuh-sys/org.muhkuh.tools-flasher

The build results from TravisCI are copied after auccess to Bintray: https://bintray.com/muhkuh/Muhkuh/flasher/view
Please note that this is done for each build, and not only tagged ones.

Build results for every commit are also available on circleci: //circleci.com/gh/muhkuh-sys/org.muhkuh.tools-flasher

Build results from a tag are released on GitHub: https://github.com/muhkuh-sys/org.muhkuh.tools-flasher/releases
