-- ldoc configuration file
title = "FlaSH, the flasher shell docs"
project = "FlaSH, the flasher shell"
format = 'markdown' --'markdown|discount|lunamark|commonmark|plain|backticks' 
output = 'index_LDOC'
description = 'short description'
full_description = 'full description'
style = '!fixed'
template = true
dir='../docs'
file = {'../lua/fsh.lua','../lua/lua/progressbar.lua','../templates/flasher.lua'}
--topics = 'Example_1.md'
