/*---------------------------------------------------------------------------
 * Please note:
 *   This file is generated by scons. All changes will be lost!
 --------------------------------------------------------------------------*/


#ifndef __FLASHER_VERSION_H__
#define __FLASHER_VERSION_H__

#define FLASHER_VERSION_MAJ ${PROJECT_VERSION_MAJ}
#define FLASHER_VERSION_MIN ${PROJECT_VERSION_MIN}
#define FLASHER_VERSION_VCS "${PROJECT_VERSION_VCS}"
#define FLASHER_VERSION_ALL "${PROJECT_VERSION}"


#endif	/* __FLASHER_VERSION_H__ */

