PROJECT_VERSION_VCS_LONG = "${PROJECT_VERSION_VCS_LONG}"
PROJECT_VERSION_MBS = "${PROJECT_VERSION}"
BUILD_TYPE = "${BUILD_TYPE}"
BUILD_TIME = "${BUILD_TIME}"
FLASHER_VERSION_STRING="netX Flasher v${PROJECT_VERSION}_${BUILD_TYPE} ${BUILD_TIME}\n    ${PROJECT_VERSION_VCS_LONG}"

