title: "FlaSH, the flasher shell"
remote_theme: pmarsceill/just-the-docs
color_scheme: nil

description: "Flasher tool v1.8.1"
baseurl: "/org.muhkuh.tools-flasher_pt" # the subpath of your site, e.g. /blog
url: "https://muhkuh-sys.github.io/" # the base hostname & protocol for your site, e.g. http://example.com

logo: "/assets/images/muhkuh_webgui.svg"

search_enabled: true


# Enable or disable heading anchors
heading_anchors: true

# Aux links for the upper right navigation
aux_links:
  "GitHub Project":
    - "//github.com/muhkuh-sys/org.muhkuh.tools-flasher_pt"

# Makes Aux links open in a new tab. Default is false
aux_links_new_tab: false


# Footer last edited timestamp
last_edit_timestamp: true # show or hide edit time - page must have `last_modified_date` defined in the frontmatter
last_edit_time_format: "%b %e %Y at %I:%M %p" # uses ruby's time format: https://ruby-doc.org/stdlib-2.7.0/libdoc/time/rdoc/Time.html

# # Footer "Edit this page on GitHub" link text
# gh_edit_link: true # show or hide edit this page link
# gh_edit_link_text: "Edit this page on GitHub"
# gh_edit_repository: "https://github.com/Yule1988/Implementation-of-svg" # the github URL for your repo
# gh_edit_branch: "master" # the branch that your docs is served from
# # gh_edit_source: docs # the source that your files originate from
# gh_edit_view_mode: "tree" # "tree" or "edit" if you want the user to jump into the editor immediately

# Back to top link
back_to_top: true
back_to_top_text: "Back to top"

# footer_content: "Copyright &copy; 2017-2020."

plugins:
  - jekyll-seo-tag

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false
