name: CI Build

on:
  push:
    branches: [ master ]
    tags:
    - '*'
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        platform:
        - # Ubuntu 20.04 x86_64
          distribution-id: ubuntu
          distribution-version: "20.04"
          cpu-architecture: x86_64
        - # Ubuntu 20.04 arm64
          distribution-id: ubuntu
          distribution-version: "20.04"
          cpu-architecture: arm64
        - # Ubuntu 22.04 x86_64
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: x86_64
        - # Ubuntu 22.04 armhf
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: armhf
        - # Ubuntu 22.04 arm64
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: arm64
        - # Ubuntu 22.04 riscv64
          distribution-id: ubuntu
          distribution-version: "22.04"
          cpu-architecture: riscv64
    container: ghcr.io/muhkuh-sys/mbs_ubuntu_2204_x86_64:latest
    steps:
    - name: Checkout repository
      # Use the old checkout v1 here. The newer v2 requires git 2.28 which is not available in the standard distribution.
      uses: actions/checkout@v1
      with:
        submodules: recursive
    - name: Build
      run: ./build_artifact.py ${{ matrix.platform.distribution-id }} ${{ matrix.platform.distribution-version }} ${{ matrix.platform.cpu-architecture }}
    - name: Upload flasher artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flasher_${{ matrix.platform.distribution-id }}_${{ matrix.platform.distribution-version }}_${{ matrix.platform.cpu-architecture }}
        path: targets/jonchki/repository/**
    - name: Upload flasher_cli artifacts
      uses: actions/upload-artifact@v4
      with:
        name: flasher_cli_${{ matrix.platform.distribution-id }}_${{ matrix.platform.distribution-version }}_${{ matrix.platform.cpu-architecture }}
        path: targets/*.tar.gz
